###############################################################################
# Created by write_sdc
# Tue Nov 12 22:23:32 2024
###############################################################################
current_design ascon_wrapper
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 25.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_clock_latency -source -min 4.5000 [get_clocks {clk}]
set_clock_latency -source -max 5.3000 [get_clocks {clk}]
set_input_delay 5.2600 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[0]}]
set_input_delay 8.5500 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[0]}]
set_input_delay 5.2600 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[1]}]
set_input_delay 8.5500 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[1]}]
set_input_delay 5.2600 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[2]}]
set_input_delay 8.5500 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[2]}]
set_input_delay 5.2600 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[3]}]
set_input_delay 8.5500 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[3]}]
set_input_delay 5.2600 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[4]}]
set_input_delay 8.5500 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[4]}]
set_input_delay 5.2600 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[5]}]
set_input_delay 8.5500 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[5]}]
set_output_delay 6.3400 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_oeb[0]}]
set_output_delay 13.3200 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_oeb[0]}]
set_output_delay 6.3400 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_oeb[10]}]
set_output_delay 13.3200 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_oeb[10]}]
set_output_delay 6.3400 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_oeb[1]}]
set_output_delay 13.3200 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_oeb[1]}]
set_output_delay 6.3400 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_oeb[2]}]
set_output_delay 13.3200 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_oeb[2]}]
set_output_delay 6.3400 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_oeb[3]}]
set_output_delay 13.3200 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_oeb[3]}]
set_output_delay 6.3400 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_oeb[4]}]
set_output_delay 13.3200 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_oeb[4]}]
set_output_delay 6.3400 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_oeb[5]}]
set_output_delay 13.3200 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_oeb[5]}]
set_output_delay 6.3400 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_oeb[6]}]
set_output_delay 13.3200 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_oeb[6]}]
set_output_delay 6.3400 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_oeb[7]}]
set_output_delay 13.3200 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_oeb[7]}]
set_output_delay 6.3400 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_oeb[8]}]
set_output_delay 13.3200 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_oeb[8]}]
set_output_delay 6.3400 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_oeb[9]}]
set_output_delay 13.3200 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_oeb[9]}]
set_output_delay 7.9000 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_out[0]}]
set_output_delay 13.1200 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_out[0]}]
set_output_delay 7.9000 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_out[1]}]
set_output_delay 13.1200 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_out[1]}]
set_output_delay 7.9000 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_out[2]}]
set_output_delay 13.1200 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_out[2]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.1900 [get_ports {io_oeb[10]}]
set_load -pin_load 0.1900 [get_ports {io_oeb[9]}]
set_load -pin_load 0.1900 [get_ports {io_oeb[8]}]
set_load -pin_load 0.1900 [get_ports {io_oeb[7]}]
set_load -pin_load 0.1900 [get_ports {io_oeb[6]}]
set_load -pin_load 0.1900 [get_ports {io_oeb[5]}]
set_load -pin_load 0.1900 [get_ports {io_oeb[4]}]
set_load -pin_load 0.1900 [get_ports {io_oeb[3]}]
set_load -pin_load 0.1900 [get_ports {io_oeb[2]}]
set_load -pin_load 0.1900 [get_ports {io_oeb[1]}]
set_load -pin_load 0.1900 [get_ports {io_oeb[0]}]
set_load -pin_load 0.1900 [get_ports {io_out[2]}]
set_load -pin_load 0.1900 [get_ports {io_out[1]}]
set_load -pin_load 0.1900 [get_ports {io_out[0]}]
set_input_transition 0.6100 [get_ports {clk}]
set_input_transition -min 0.0500 [get_ports {io_in[5]}]
set_input_transition -max 0.3800 [get_ports {io_in[5]}]
set_input_transition -min 0.0500 [get_ports {io_in[4]}]
set_input_transition -max 0.3800 [get_ports {io_in[4]}]
set_input_transition -min 0.0500 [get_ports {io_in[3]}]
set_input_transition -max 0.3800 [get_ports {io_in[3]}]
set_input_transition -min 0.0500 [get_ports {io_in[2]}]
set_input_transition -max 0.3800 [get_ports {io_in[2]}]
set_input_transition -min 0.0500 [get_ports {io_in[1]}]
set_input_transition -max 0.3800 [get_ports {io_in[1]}]
set_input_transition -min 0.0500 [get_ports {io_in[0]}]
set_input_transition -max 0.3800 [get_ports {io_in[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 1.5000 [current_design]
set_max_fanout 30.0000 [current_design]
